### ISSUE TITLE
cant use vuedoc/md to gen md file

### ISSUE THREAD

**Issue by wuchuguang** [vuedoc/md#17]
```
const vuedoc = require('@vuedoc/md/lib/cli').exec;
const fs = require('fs');
const path = require('path');
const realPath = path.resolve(__dirname, 'src/components');
let components = fs.readdirSync(realPath);
components = components.map(component => {
    return path.resolve(realPath, component)
});
const destPath = path.resolve(__dirname, 'doc/components');
components.forEach(async component =>{
    try{
        await vuedoc([component, '--output', destPath]);
    }catch (e) {
        console.log(e.message)
    }
});
```

report  error

```
Node {
  type: 'ExperimentalSpreadProperty',
  start: 189,
  end: 361,
  range: [ 189, 361 ],
  argument: 
   Node {
     type: 'CallExpression',
     start: 192,
     end: 361,
     range: [ 192, 361 ],
     callee: 
      Node {
        type: 'Identifier',
        start: 192,
        end: 202,
        range: [Array],
        name: 'mapActions' },
     arguments: [ [Node] ] } }
/opt/source-code/erp_web/trunk/vue-deskop/node_modules/@vuedoc/parser/lib/utils.js:114
  if (property.key.type === 'Literal') {
                   ^

TypeError: Cannot read property 'type' of undefined
    at Object.value (/opt/source-code/erp_web/trunk/vue-deskop/node_modules/@vuedoc/parser/lib/utils.js:114:20)
    at property.value.properties.forEach (/opt/source-code/erp_web/trunk/vue-deskop/node_modules/@vuedoc/parser/lib/parser.js:97:27)
    at Array.forEach (<anonymous>)
    at Parser.parseObjectExpression (/opt/source-code/erp_web/trunk/vue-deskop/node_modules/@vuedoc/parser/lib/parser.js:88:31)
    at Parser.extractProperties (/opt/source-code/erp_web/trunk/vue-deskop/node_modules/@vuedoc/parser/lib/parser.js:169:14)
    at body.declaration.properties.forEach (/opt/source-code/erp_web/trunk/vue-deskop/node_modules/@vuedoc/parser/lib/parser.js:232:70)
    at Array.forEach (<anonymous>)
    at ast.body.forEach (/opt/source-code/erp_web/trunk/vue-deskop/node_modules/@vuedoc/parser/lib/parser.js:232:43)
    at Array.forEach (<anonymous>)
    at process.nextTick (/opt/source-code/erp_web/trunk/vue-deskop/node_modules/@vuedoc/parser/lib/parser.js:211:21)

```

**Comment by demsking** [comment]
Please try with the [`vuedoc.md's API`](https://github.com/vuedoc/md#programmatic-usage) and the `options.filenames` option.
Let me know if you still have errors.

**Comment by demsking** [comment]
**This project and its issues has been moved to https://gitlab.com/vuedoc/md**
